# Do not forget to add DOCKERHUB_USERNAME and DOCKERHUB_TOKEN to Settings/Secrets and variables/Actions
# Docker files > build-context
# .yml files > .github/workflows/

name: Build and Push Docker image to Docker Hub

on:
  push:
    branches:
      - ci/extended

jobs:
  prepare:
    name: Prepare
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          tags: kivanc57/printf:latest #DockerHub repo
  
  # test:
  #   name: Test Docker Image
  #   runs-on: ubuntu-latest
  #   needs: build
  #   steps:
  #     - name: test
  #       uses: docker run --rm kivanc57/printf:latest <some-test-command>

  deploy:
    name: Push Docker Image to Docker Hub
    runs-on: ubuntu-latest
    needs: [prepare, build] # In case of tests ==> [prepare, build, test]
    steps:
      - name: Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: kivanc57/printf:latest
